export function MathDistance( p1: number[], p2: number[] ): number;
export function wholeDistance( points: number[][] ): number;
export function getBaseLength( points: number[][] ): number;
export function Mid( p1: number[], p2: number[] ): number[];
export function getAzimuth( startPnt: number[], endPnt: number[] ): number;
export function getAngleOfThreePoints( a: number[], b: number[], c: number[] ): number;
export function isClockWise( p1: number[], p2: number[], p3: number[] ): boolean;
export function getThirdPoint( startPnt: number[], endPnt: number[], angle: number, distance: number, clockWise: boolean ): number[];
export function getNormal( p1: number[], p2: number[], p3: number[] ): number[];
export function getBisectorNormals( t: number, p1: number[], p2: number[], p3: number[] ): number[][];
export function getCurvePoints( t: number, controlPoints: number[][] ): number[][];
export function getQBSplinePoints( points: number[][] ): number[][];
export function createStraightArrow( p1: number[], p2: number[], headSize: number ): number[][];
export function createFineArrow( p1: number[], p2: number[] ): number[][];
export function createCurvedArrow( lnglatPoints: number[][] ): number[][];
export function createAttackArrow( lnglatPoints: number[][] ): number[][];
